NewsPortal/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('news.urls')),
]

news/urls.py
# # Путь: news/urls.py

from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from . import views


from .views_auth import (
    RegisterView,
    ActivateAccountView,
    LoginView,
    ProfileView,
    ChangePasswordView,
    PermissionDeniedView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
)


from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleEditView,
    ArticleDeleteView,
    ArticleSearchView,
)


urlpatterns = [
    # Главная страница
    path('', views.home, name='home'),

    # Административная панель
    path('admin/', admin.site.urls),

    # Просмотр и детали статей и новостей
    # path('news/', views.article_list, name='article_list'),
    path('news/', ArticleListView.as_view(), name='article_list'),
    # path('news/<int:id>/', views.article_detail, name='article_detail'),
    path('news/<int:id>/', ArticleDetailView.as_view(), name='article_detail'),

    # Поиск статей и новостей
    # path('news/search/', article_search, name='article_search'),
    path('news/search/', ArticleSearchView.as_view(), name='article_search'),


    # Универсальные маршруты для создания, редактирования и удаления статей и новостей
    # path('create/', create_post, name='create_post'),  # Универсальный маршрут для создания статей и новостей
    path('create/', ArticleCreateView.as_view(), name='create_post'),
    # path('edit/<int:pk>/', edit_post, name='edit_post'),  # Универсальный маршрут для редактирования статей и новостей
    path('edit/<int:pk>/', ArticleEditView.as_view(), name='edit_post'),
    # path('delete/<int:pk>/', delete_post, name='delete_post'),  # Универсальный маршрут для удаления статей и новостей
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete_post'),


    # path('login/', auth_views.LoginView.as_view(template_name='news/login.html'), name='login'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name='register'),
    path('register/', RegisterView.as_view(), name='register'),

    # Профиль пользователя и изменение пароля
    # path('profile/', views.profile_view, name='profile'),
    path('profile/', ProfileView.as_view(), name='profile'),
    # path('edit_profile/', edit_profile, name='edit_profile'),
    path('edit_profile/', ProfileView.as_view(), name='edit_profile'),
    # path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),


    # Разрешение на доступ
    # path('permission_denied/', views.permission_denied_view, name='permission_denied'),
    path('permission-denied/', PermissionDeniedView.as_view(), name='permission_denied'),

    # Подписка на категорию
    path('subscribe/<int:category_id>/', views.subscribe_to_category, name='subscribe_to_category'),

    # Временное решение: перенаправление с /accounts/login/ на /login/
    path('accounts/', include('allauth.urls')),
    path('accounts/login/', lambda request: redirect('login'), name='accounts_login_redirect'),

    # URL, который будет обрабатывать активацию пользователя при переходе по ссылке.
    # path('activate/<int:user_id>/', views.activate_account, name='activate_account'),
    path('activate/<int:user_id>/', ActivateAccountView.as_view(), name='activate_account'),


    # Сброс пароля по email
    # Маршрут для запроса сброса пароля
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='news/password_reset.html'),
         name='password_reset'),

    # Маршрут для уведомления об отправке письма
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='news/password_reset_done.html'),
         name='password_reset_done'),

    # Маршрут для сброса пароля по ссылке из письма
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='news/password_reset_confirm.html'),
         name='password_reset_confirm'),

    # Изменение пароля для авторизованных пользователей
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),  # Форма изменения пароля
    path('password-change-done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),  # Уведомление об успешной смене пароля


    # Маршрут для уведомления об успешном сбросе пароля
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='news/password_reset_complete.html'),
         name='password_reset_complete'),


    # Проверка лимита постов перед перенаправлением на создание
    path('check_post_limit/', views.check_post_limit, name='check_post_limit'),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
# from . import signals

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField(max_length=25, unique=False, verbose_name='Name of category')
    subscribers = models.ManyToManyField(User, related_name='categories', blank=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name



class Rating(models.Model):
    value = models.IntegerField(unique=True)  # Значение рейтинга от 1 до 5

    def __str__(self):
        return str(self.value)

# models.py

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    publication_date = models.DateField()
    author_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=9)
    article_type = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    rating = models.ForeignKey(Rating, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_author = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


# models.py

news/forms.py
# forms.py

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm

from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

class CustomUserChangeForm(UserChangeForm):
    ACCOUNT_TYPE_CHOICES = [(False, 'Simple'), (True, 'Premium')]
    USER_TYPE_CHOICES = [(False, 'Reader'), (True, 'Author')]

    # account_type = forms.ChoiceField(choices=ACCOUNT_TYPE_CHOICES, label="Account type", required=True, widget=forms.Select)
    # is_author = forms.ChoiceField(choices=USER_TYPE_CHOICES, label="User type", required=True, widget=forms.Select)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['password'].help_text = 'Чтобы изменить пароль вернитесь на страницу Профиль и выберите Изменить пароль'

    def save(self, commit=True):
        user = super(CustomUserChangeForm, self).save(commit=False)
        if commit:
            user.save()  # Сохраняем изменения пользователя
        return user

class CustomUserCreationForm(UserCreationForm):
    # Определяем поля с выпадающими списками
    ACCOUNT_TYPE_CHOICES = [(False, 'Simple'), (True, 'Premium')]
    USER_TYPE_CHOICES = [(False, 'Reader'), (True, 'Author')]

    # account_type = forms.ChoiceField(choices=ACCOUNT_TYPE_CHOICES, label="Account type", required=True,
    #                                  widget=forms.Select)
    # is_author = forms.ChoiceField(choices=USER_TYPE_CHOICES, label="User type", required=True, widget=forms.Select)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.is_active = True
        user.set_password(self.cleaned_data['password1'])  # Сохраняем зашифрованный пароль
        if commit:
            user.save()
        return user

news/Temp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article, News
from .filters import ArticleFilter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from datetime import date
from django.utils import timezone

def home(request):
    return render(request, 'news/home.html')

def edit_news(request, pk):
    article = get_object_or_404(Article, pk=pk, type=True)
    if request.method == 'POST':
        title = request.POST.get('title')
        author = request.POST.get('author')
        content = request.POST.get('content')

        if not title or not author or not content:
            return render(request, 'news/edit_news.html', {
                'error': 'Все поля должны быть заполнены.',
                'article': article
            })

        article.title = title
        article.author = author
        article.content = content
        article.publication_date = timezone.now()
        article.save()
        return redirect('article_detail', id=article.pk)

    return render(request, 'news/edit_news.html', {'article': article})

def edit_article(request, pk):
    article = get_object_or_404(Article, pk=pk, type=False)
    if request.method == 'POST':
        title = request.POST.get('title')
        author = request.POST.get('author')
        content = request.POST.get('content')

        if not title or not author or not content:
            return render(request, 'news/edit_article.html', {
                'error': 'Все поля должны быть заполнены.',
                'article': article
            })

        article.title = title
        article.author = author
        article.content = content
        article.publication_date = timezone.now()
        article.save()
        return redirect('article_detail', id=article.pk)

    return render(request, 'articles/edit_article.html', {'article': article})

@login_required
def delete_news(request, pk):
    item = get_object_or_404(Article, pk=pk, type=True)  # Убедитесь, что тип записи - новость
    if request.method == 'POST':
        item.delete()
        return redirect('article_list')  # Или другой URL для отображения списка новостей
    return render(request, 'news/delete_news.html', {'item': item})


@login_required
def delete_article(request, pk):
    item = get_object_or_404(Article, pk=pk, type=False)  # Убедитесь, что тип записи - статья
    if request.method == 'POST':
        item.delete()
        return redirect('article_list')  # Или другой URL для отображения списка статей
    return render(request, 'articles/delete_article.html', {'item': item})






def article_list(request):
    articles = Article.objects.all().order_by('-publication_date')
    paginator = Paginator(articles, 10)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)
    return render(request, 'news/article_list.html', {'page_obj': page_obj})

def article_detail(request, id):
    article = get_object_or_404(Article, id=id)
    return render(request, 'news/article_detail.html', {'article': article})

@login_required
def admin_page(request):
    if request.method == 'POST':
        # Очистка старых данных сессии перед обработкой новых действий
        request.session.pop('edit_mode', None)
        request.session.pop('delete_mode', None)

        record_type = request.POST.get('record_type')

        # Обработка кнопки "Создать новую запись"
        if 'create' in request.POST:
            if record_type == 'news':
                return redirect('create_news')
            elif record_type == 'article':
                return redirect('create_article')

        # Обработка кнопки "Редактировать запись"
        elif 'edit' in request.POST:
            # Передаем параметры через сессию
            request.session['edit_mode'] = True
            request.session['delete_mode'] = False
            request.session['record_type'] = record_type
            return redirect('article_search')

        # Обработка кнопки "Удалить запись"
        elif 'delete' in request.POST:
            # Передаем параметры через сессию
            request.session['edit_mode'] = False
            request.session['delete_mode'] = True
            request.session['record_type'] = record_type
            return redirect('article_search')

    return render(request, 'news/admin_page.html')


def article_search(request):
    # Проверка значения радиокнопок и выполнение соответствующего фильтрации
    filterset = ArticleFilter(request.GET, queryset=Article.objects.all().order_by('-publication_date'))
    edit_mode = request.GET.get('edit_mode') == 'true'
    delete_mode = request.GET.get('delete_mode') == 'true'

    # Проверяем, были ли отправлены критерии поиска
    if any(request.GET.getlist(k) for k in filterset.form.fields):
        paginator = Paginator(filterset.qs, 10)
        page_number = request.GET.get('page')
        try:
            page_obj = paginator.get_page(page_number)
        except PageNotAnInteger:
            page_obj = paginator.get_page(1)
        except EmptyPage:
            page_obj = paginator.get_page(paginator.num_pages)


        show_edit_button = edit_mode and filterset.qs.count() == 1
        show_delete_button = delete_mode and filterset.qs.count() == 1

        return render(request, 'news/article_search.html', {
            'filterset': filterset,
            'page_obj': page_obj,
            'show_edit_button': show_edit_button,
            'show_delete_button': show_delete_button,
        })
    else:
        return render(request, 'news/article_search.html', {
            'filterset': filterset,
        })




def create_news(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        author = request.POST.get('author')
        content = request.POST.get('content')

        if not title or not author or not content:
            return render(request, 'news/create_news.html', {
                'error': 'Все поля должны быть заполнены.'
            })

        Article.objects.create(
            title=title,
            author=author,
            content=content,
            publication_date=date.today(),
            type=True
        )
        return redirect('admin_page')
    return render(request, 'news/create_news.html')

def create_article(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        author = request.POST.get('author')
        content = request.POST.get('content')

        if not title or not author or not content:
            return render(request, 'news/create_article.html', {
                'error': 'Все поля должны быть заполнены.'
            })

        Article.objects.create(
            title=title,
            author=author,
            content=content,
            publication_date=date.today(),
            type=False
        )
        return redirect('admin_page')
    return render(request, 'news/create_article.html')



@login_required
def delete_news(request, pk):
    item = get_object_or_404(Article, pk=pk, type=True)  # Убедитесь, что тип записи - новость
    if request.method == 'POST':
        item.delete()
        return redirect('article_list')  # Или другой URL для отображения списка новостей
    return render(request, 'news/delete_news.html', {'item': item})

@login_required
def delete_article(request, pk):
    item = get_object_or_404(Article, pk=pk, type=False)  # Убедитесь, что тип записи - статья
    if request.method == 'POST':
        item.delete()
        return redirect('article_list')  # Или другой URL для отображения списка статей
    return render(request, 'articles/delete_article.html', {'item': item})

news/templates/news/admin_page.html
{% extends 'news/default.html' %}

{% block title %}Административная страница{% endblock %}

{% block header %}Административная часть{% endblock %}

{% block content %}
    <div class="container mt-4">
        <!-- Форма для кнопки Создать новую запись -->
        <form method="post" action="{% url 'create_news' %}">
            {% csrf_token %}
            <div class="mb-4">
                <button type="submit" name="create" class="btn btn-primary">
                    Создать новую запись
                </button>
            </div>
        </form>

        <!-- Форма для кнопки Редактировать запись -->
        <form method="post" action="{% url 'article_search' %}">
            {% csrf_token %}
            <div class="mb-4">
                <input type="hidden" name="edit_mode" value="true">
                <input type="hidden" name="delete_mode" value="false">
                <input type="hidden" name="record_type" value="{{ request.POST.record_type }}">
                <button type="submit" name="edit" class="btn btn-secondary">Редактировать или удалить запись</button>
            </div>
        </form>
    </div>
{% endblock %}

news/templates/news/article_search.html
{# Путь: news/templates/news/article_search.html #}
{% extends 'news/default.html' %}

{% load static %}

{% block title %}Поиск публикации{% endblock %}

{% block header %}Поиск публикации{% endblock %}

{% block content %}

    <!-- Подключение стилей -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- Отображение количества найденных публикаций -->
   <h2>
       Количество публикаций по запросу:
       {% if page_obj %}
           {{ filterset.qs.count|default:0 }}
       {% else %}
           0
       {% endif %}
   </h2>


    <!-- Фильтр публикаций и сброс -->
    <div class="row">
        <h2 class="col-md-6">Фильтр публикаций</h2>
        <div class="col-md-6 text-end">
            <a href="{% url 'article_search' %}" class="btn btn-warning btn-reset">Сбросить все фильтры</a>
        </div>
    </div>


    <form method="get" class="filter-form">
        <!-- Контейнер для всех блоков фильтров -->
        <div class="filter-container">

            <!-- (фильтры для названия) -->
            <div class="filter-block title-filter">
                <label for="id_title">Название содержит</label>
                <div class="input-container">
                    {{ filterset.form.title }}
                </div>
            </div>

            <!-- (фильтры для содержания) -->
            <div class="filter-block content-filter">
                <label for="id_content">Текст содержит</label>
                <div class="input-container">
                    {{ filterset.form.content }}
                </div>
            </div>

            <!-- (фильтры для рейтинга) -->
            <div class="filter-block rating-filter">
                <label for="id_type">Рейтинг</label>
                <div class="input-container">
                    <select name="type" class="form-control">
                        <option value="">Все</option>
                        {% for rating in ratings %}
                            <option value="{{ rating.value }}" {% if request.GET.type == rating.value|stringformat:"d" %}selected{% endif %}>{{ rating.value }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>


            <!-- (фильтры для автора) -->
            <div class="filter-block author-filter">
                <label for="id_author">Автор</label>
                <div class="input-container">
                    <select name="author_profile" id="id_author" class="form-control">
                        <option value="">Все</option>
                        {% for author in authors %}
                            <option value="{{ author.id }}">{{ author.first_name }} {{ author.last_name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- (фильтры для категории) -->
            <div class="filter-block category-filter">
                <label for="id_category">Категория</label>
                <div class="input-container">
                    <select name="category" id="id_category">
                        <option value="">Выберите категорию</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- (фильтры для типа статьи) -->
            <div class="filter-block type-filter">
                <label for="id_type">Тип статьи</label>
                <div class="input-container">
                    <select name="article_type" class="form-control">
                        <option value="">Все</option>
                        <option value="1" {% if request.GET.article_type == '1' %}selected{% endif %}>Статья</option>
                        <option value="0" {% if request.GET.article_type == '0' %}selected{% endif %}>Новость</option>
                    </select>
                </div>
            </div>

            <!-- (фильтры для названия) -->
            <div class="filter-block date-filter">
                <label for="id_publication_date">Дата публикации</label>
                <div class="input-container">
                    {{ filterset.form.publication_date }}
                </div>
            </div>

            <div class="filter-block find-button">
                <button type="submit" class="btn btn-primary">Найти</button>
            </div>
        </div>
    </form>

    <!-- Отображение результатов поиска -->
    <div class="search-results">
        {% if page_obj %}
            <h2>Результаты поиска:</h2>
        <ul class="result-list">
            {% for article in page_obj %}
                <li class="result-item">

                    <div class="result-details">
                        <div><strong class="label">Автор:</strong> <span class="author">{{ article.author_profile.user.first_name }} {{ article.author_profile.user.last_name }}</span></div>
                        <div><strong class="label">Дата:</strong> <span class="date">{{ article.publication_date|date:"d.m.Y" }}</span></div>
                        <div><strong class="label">Категория:</strong> <span class="category">{{ article.category.name }}</span></div>
                        <div><strong class="label">Рейтинг:</strong> <span class="title">{{ article.rating.value|default:"Рейтинга пока нет" }}</span></div>

                        <div><strong class="label">Тип:</strong>
                            <span class="title">{{ article.article_type|yesno:"Новость,Статья" }}</span>
                        </div>
                    </div>

                    <div class="result-content">
                        <div><strong class="label">Название:</strong> <span class="title">{{ article.title }}</span></div>
                        <span><strong>Содержание:</strong> {{ article.content|slice:":40" }}...&nbsp;&nbsp;&nbsp;<a href="{% url 'article_detail' article.id %}">Читать полностью</a></span>
                    </div>





                    <!-- Кнопки редактирования и удаления (если одна запись) -->
                    {% if page_obj.paginator.count == 1 %}
                        <div class="edit-delete-buttons">
                            {% if user.is_authenticated %}
                                {% if user.is_superuser or user == article.author_profile.user %}
                                    <!-- Если пользователь автор или суперпользователь -->
                                    {% if article.article_type %}
                                        <!-- Пример ссылки для редактирования новости -->
                                        <a href="{% url 'edit_post' article.id %}?article_type=1" class="btn btn-primary">Редактировать</a>
                                        <a href="{% url 'delete_post' article.id %}?article_type=1" class="btn btn-danger">Удалить</a>
                                    {% else %}
                                        <!-- Пример ссылки для редактирования статьи -->
                                        <a href="{% url 'edit_post' article.id %}?article_type=0" class="btn btn-primary">Редактировать</a>
                                        <a href="{% url 'delete_post' article.id %}?article_type=0" class="btn btn-danger">Удалить</a>
                                    {% endif %}
                                {% else %}
                                    <!-- Перенаправление на страницу permission_denied.html, если нет прав -->
                                    <script>
                                        window.location.href = "{% url 'permission_denied' %}";
                                    </script>
                                {% endif %}
                            {% else %}
                                <!-- Перенаправление на страницу permission_denied.html, если не аутентифицирован -->
                                <script>
                                    window.location.href = "{% url 'permission_denied' %}";
                                </script>
                            {% endif %}
                        </div>
                    {% endif %}





                </li>
            {% empty %}
                <p>Нет результатов.</p>
            {% endfor %}
        </ul>

            <!-- Пагинация -->
            {% if page_obj.has_other_pages %}
                <div class="pagination">
                    {% if page_obj.has_previous %}
                        <a href="?{{ filter_params }}&page=1" title="Первая страница">«</a>
                        <a href="?{{ filter_params }}&page={{ page_obj.previous_page_number }}" title="Предыдущая страница">‹</a>
                    {% else %}
                        <span class="disabled">«</span>
                        <span class="disabled">‹</span>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <span class="current">{{ num }}</span>
                        {% else %}
                            <a href="?{{ filter_params }}&page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <a href="?{{ filter_params }}&page={{ page_obj.next_page_number }}" title="Следующая страница">›</a>
                        <a href="?{{ filter_params }}&page={{ page_obj.paginator.num_pages }}" title="Последняя страница">»</a>
                    {% else %}
                        <span class="disabled">›</span>
                        <span class="disabled">»</span>
                    {% endif %}
                </div>
            {% endif %}


        {% endif %}
    </div>

{% endblock %}

news/templates/news/create_news.html
{% extends 'news/default.html' %}

{% block title %}Создание новости{% endblock %}

{% block header %}Создание новости{% endblock %}

{% block content %}
    <h2>СОЗДАНИЕ НОВОСТИ</h2>

    <!-- Отображение имени и фамилии автора -->
    <h3>Автор: {{ request.user.first_name }} {{ request.user.last_name }}</h3>

    <form method="post">
        {% csrf_token %}
        <label>Название новости:</label>
        <input type="text" name="title" required>
        <br>

        <!-- Добавляем выбор категории -->
        <label for="id_category">Категория:</label>
        <select name="category" id="id_category">
            <option value="">Выберите категорию</option>
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <br>

        <label>Содержание:</label>
        <textarea name="content" required></textarea>
        <br>
        <button type="submit">Записать</button>
    </form>

    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}
{% endblock %}

news/templates/news/delete_news.html
{% extends 'news/default.html' %}

{% block title %}Удаление новости{% endblock %}

{% block header %}УДАЛЕНИЕ НОВОСТИ{% endblock %}

{% block content %}
<div class="container mt-4">
    <form method="post">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="title">Название новости</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ item.title }}" readonly>
        </div>

        <div class="form-group mb-4">
            <label for="author">Автор</label>
            <input type="text" class="form-control" id="author" name="author" value="{{ item.author }}" readonly>
        </div>

        <div class="form-group mb-4">
            <label for="content">Содержание</label>
            <textarea class="form-control" id="content" name="content" rows="6" readonly>{{ item.content }}</textarea>
        </div>

        <div class="form-group mb-4">
            <label for="publication_date">Дата публикации</label>
            <input type="text" class="form-control" id="publication_date" name="publication_date" value="{{ item.publication_date|date:"d.m.Y" }}" readonly>
        </div>

        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>
{% endblock %}

news/templates/news/home.html
<!-- Путь: templates/news/home.html -->

{% extends 'news/default.html' %}

{% load static %}

{% block title %}Главная страница{% endblock %}

{% block header %}Главная страница{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Это информационный портал</h1>

        <!-- Добавление изображения под текстом -->
        <div class="image-container mt-3">
            <img src="{% static 'pictures/Novosti.jpg' %}" alt="Изображение новостного портала" style="width: 100%; max-width: 600px;">
        </div>

        <p>Добро пожаловать на наш новостной портал!</p>
        <p>Перейдите в раздел <a href="{% url 'article_list' %}">новостей</a>, чтобы увидеть последние события.</p>

    </div>
{% endblock %}

news/templates/news/login.html
{% extends 'news/default.html' %}

{% block title %}Войти{% endblock %}

{% block content %}
<div class="login-container" style="display: flex; justify-content: center; align-items: center; height: 50vh;">
    <div class="login-box" style="border: 1px solid #ccc; padding: 20px; width: 300px; text-align: center;">
        <h2>Вход</h2>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
        <div style="margin-top: 10px;">
            <a href="{% url 'register' %}">Зарегистрироваться</a><br><br>
            <a href="{% url 'password_reset' %}">Забыл пароль?</a>
        </div>
    </div>
</div>
{% endblock %}